import { createSwaggerSpec } from 'next-swagger-doc';

export const getApiDocs = () => {
  const spec = createSwaggerSpec({
    apiFolder: 'src/app/api/swaggerDocs', // ou 'pages/api' si Pages Router
    definition: {
      openapi: '3.0.0', 
      info: {
        title: 'Ocoofee API Documentation site de e-commerce de café',
        version: '1.0.0',
        description: 'API Documentation for the Ocoofee e-commerce site',
        contact: {
          name: 'Mario Souvily',
          url: 'https://mariosouvily.com',
          email: 'mariosouvily@gmail.com',
        },
        license: {
          name: 'MIT',
      },
      servers: [
        {
          url: 'http://localhost:3000',
          description: 'Local server',
        },
        {
          url: '',
          description: 'Production server',
        },
      ],
      components: {
        schemas: {
          User: {
            type: 'object',
            properties: {
              id: { type: 'number' },
              prenom: { type: 'string',
                example: 'John Doe',
               },
              nom: { type: 'string',
                example: 'Doe',
               },
              email: { type: 'string',
                example: 'john.doe@example.com',
               },
              role: { type: 'boolean',
                example: false,
               },
              createdAt: { type: 'string', format: 'date-time',
                example: '2021-01-01T00:00:00.000Z',
               },
              updatedAt: { type: 'string', format: 'date-time',
                example: '2021-01-01T00:00:00.000Z',
               },
            },
          },
          Cafe: {
            type: 'object',
            properties: {
              id: { type: 'number' },
              nom: { type: 'string',
                example: 'Café en grain Éthiopie Moka',
               },
              type: { type: 'string',
                example: 'Arabica',
               },
              origine: { type: 'string',
                example: 'Éthiopie',
               },
              quantite: { type: 'string',
                example: '250g',
               },
              description: { type: 'string',
                example: 'Un café floral et fruité aux notes de jasmin et bergamote.',
               },
              prix: { type: 'number',
                example: 8.9,
               },
              image: { type: 'string',
                example: '/image/cafe/ethiopie-moka.jpg',
               },
              categorie: { type: 'string',
                example: 'grain',
                enum: ['grain', 'moulu'],
                
               },
            },
          },
          Commande: {
            type: 'object',
            properties: {
              id: { type: 'number',
                example: 1,
               },
              date: { type: 'string', format: 'date-time',
                example: '2021-01-01T00:00:00.000Z',
               },
              prix: { type: 'number',
                example: 8.9,
               },
                adresse: { type: 'string',
                example: '123 Rue de la Paix, Paris, France',
               },
              userId: { type: 'number',
                example: 1,
               },
              createdAt: { type: 'string', format: 'date-time',
                example: '2021-01-01T00:00:00.000Z',
               },
              updatedAt: { type: 'string', format: 'date-time',
                example: '2021-01-01T00:00:00.000Z',
               },
            },
          },
          CommandeItem: {
            type: 'object',
            properties: {
              id: { type: 'number',
                example: 1,
               },
              commandeId: { type: 'number',
                example: 1,
               },
              cafeId: { type: 'number',
                example: 1,
               },
              quantite: { type: 'number',
                example: 1,
               },
              prix: { type: 'number',
                example: 8.9,
               },
            },
          },
          Cart: {
            type: 'object',
            properties: {
                id: { type: 'number',
                example: 1,
               },
              userId: { type: 'number',
                example: 1,
               },
              createdAt: { type: 'string', format: 'date-time',
                example: '2021-01-01T00:00:00.000Z',
               },
              updatedAt: { type: 'string', format: 'date-time',
                example: '2021-01-01T00:00:00.000Z',
               },
            },
          },
          CartItem: {
            type: 'object',
            properties: {
              id: { type: 'number',
                example: 1,
               },
              cartId: { type: 'number',
                example: 1,
               },
              cafeId: { type: 'number',
                example: 1,
               },
              quantite: { type: 'number',
                example: 1,
               },
              prix: { type: 'number',
                example: 8.9,
               },
            },
          },
          
          
        },
      },
    },
  },
});
  return spec;
};