name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Run ESLint
        run: npm run lint

      # Optionnel: ajoute un step Prettier si un script "format" existe
      # - name: Check Prettier formatting
      #   run: npm run format
